# DeclareGlobalFunction( "VnutVnesh" );
 DeclareGlobalFunction( "ContractMiniFace" );
 DeclareGlobalFunction( "DivideFace" );
 DeclareGlobalFunction( "FirstBoundary" );
 DeclareGlobalFunction( "FreeUnionPol" );
 DeclareGlobalFunction( "IsPolytope" );
 DeclareGlobalFunction( "PermFaces" );
 DeclareGlobalFunction( "PolBoundary" );
 DeclareGlobalFunction( "PolMinusFaceDoublingMethod" );
 DeclareGlobalFunction( "SetOfFacesBoundary" );
 DeclareGlobalFunction( "FaceComp" );
 DeclareGlobalFunction( "sphereTriangul" );
 DeclareGlobalFunction( "ballTriangul" );
 DeclareGlobalFunction( "StarFace" );
 DeclareGlobalFunction( "SubPolytope" );
# DeclareGlobalFunction( "TriangulateFace" );
 DeclareGlobalFunction( "dataPachner" );
 DeclareGlobalFunction( "FromSimplexToPolytope" );
